apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-media
  namespace: pedroflix
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: pedroflix-local
  volumeName: pv-media
  resources:
    requests:
      storage: 250Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-downloads
  namespace: pedroflix
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: pedroflix-local
  volumeName: pv-downloads
  resources:
    requests:
      storage: 40Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-config-jellyfin
  namespace: pedroflix
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: pedroflix-local
  volumeName: pv-config-jellyfin
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-config-radarr
  namespace: pedroflix
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: pedroflix-local
  volumeName: pv-config-radarr
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-config-sonarr
  namespace: pedroflix
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: pedroflix-local
  volumeName: pv-config-sonarr
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-config-prowlarr
  namespace: pedroflix
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: pedroflix-local
  volumeName: pv-config-prowlarr
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-config-bazarr
  namespace: pedroflix
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: pedroflix-local
  volumeName: pv-config-bazarr
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-config-qbittorrent
  namespace: pedroflix
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: pedroflix-local
  volumeName: pv-config-qbittorrent
  resources:
    requests:
      storage: 1Gi
