apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: pedroflix
  labels:
    app: bazarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      nodeSelector:
        role: media
      tolerations:
        - key: dedicated
          operator: Equal
          value: media
          effect: NoSchedule
      containers:
        - name: bazarr
          image: lscr.io/linuxserver/bazarr:latest
          ports:
            - containerPort: 6767
              name: http
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Sao_Paulo"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /movies
              subPath: movies
            - name: media
              mountPath: /tv
              subPath: tv
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 6767
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: pvc-config-bazarr
        - name: media
          persistentVolumeClaim:
            claimName: pvc-media
