apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: pedroflix
  labels:
    app: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      nodeSelector:
        role: media
      tolerations:
        - key: dedicated
          operator: Equal
          value: media
          effect: NoSchedule
      containers:
        - name: sonarr
          image: lscr.io/linuxserver/sonarr:latest
          ports:
            - containerPort: 8989
              name: http
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Sao_Paulo"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /tv
              subPath: tv
            - name: downloads
              mountPath: /downloads
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 8989
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: pvc-config-sonarr
        - name: media
          persistentVolumeClaim:
            claimName: pvc-media
        - name: downloads
          persistentVolumeClaim:
            claimName: pvc-downloads
