apiVersion: v1
kind: ConfigMap
metadata:
  name: configarr-config
  namespace: pedroflix
data:
  config.yml: |
    trashGuideUrl: https://github.com/TRaSH-Guides/Guides
    recyclarrConfigUrl: https://github.com/recyclarr/config-templates

    sonarr:
      main:
        base_url: http://sonarr.pedroflix.svc.cluster.local:8989
        api_key: !secret sonarr_api_key

        include:
          - template: sonarr-quality-definition-series
          - template: sonarr-v4-quality-profile-web-1080p
          - template: sonarr-v4-custom-formats-web-1080p

    radarr:
      main:
        base_url: http://radarr.pedroflix.svc.cluster.local:7878
        api_key: !secret radarr_api_key

        include:
          - template: radarr-quality-definition-movie
          - template: radarr-quality-profile-hd-bluray-web
          - template: radarr-custom-formats-hd-bluray-web
